### ISSUE TITLE
Ajout d'un tag (release) sur la v1.0.0 du schéma

### ISSUE THREAD

**Issue by geoffreyaldebert** [NaturalSolutions/schema-arbre#1]
Bonjour,

Bravo et merci pour le temps pris pour réaliser ce schéma.

Afin de pouvoir s'interfacer correctement avec schema.data.gouv.fr, il faudrait que vous ajoutiez une release de ce repo via la création d'un tag Github. Vous pouvez prendre exemple sur https://github.com/etalab/schema-lieux-covoiturage et https://github.com/etalab/schema-lieux-covoiturage/tags 

Ce tag permettra de figer une version du schéma dans le temps et permettra d'éviter les erreurs lors du développement d'éventuelles nouvelles fonctionnalités sur le master (schema.data.gouv.fr ne s'interface qu'avec des releases de schéma).

A votre disposition si besoin d'aide,
Geoffrey

**Comment by mfredout** [comment]
J'ai créé le tag v0.1.0
