### ISSUE TITLE
Quel est le "scope" du champs "id"

### ISSUE THREAD

**Issue by pchampin** [NaturalSolutions/schema-arbre#18]
La documentation du champs `id` indique :
> un identifiant unique de l'objet arbre

mais ça n'est pas très informatif. Unique à quelle échelle ? À l'échelle du fichier lui même, de la commune, communauté de commune, du pays ?

Par ailleurs, quelle est le scope temporel de cette identifiant ? Est-ce que le même arbre doit forcément avoir le même identifiant dans deux versions successives du fichier ?

**Comment by mfredout** [comment]
Bonjour, 

Merci pour cette question, nous allons mettre à jour la définition pour que ça soit plus clair. L'idée est que le champs ID soit unique au sein d'un même fichier et dans le suivi temporel que les personnes qui publient à nouveau gardent le même identifiant pour un individu (au même titre que le matricule d'un arbre).
