### ISSUE TITLE
Réparer les URL des fichiers exemples

### ISSUE THREAD

**Issue by johanricher** [NaturalSolutions/schema-arbre#3]
Bravo pour ce nouveau schéma qui va je pense rencontrer un certain succès ! :clap: Je vous encourage à contacter OpenDataFrance car cela mériterait d'être popularisé auprès des collectivités dans le cadre du [SCDL](https://scdl.opendatafrance.net/docs/). :+1: 

J'ai cependant constaté un petit problème pas compliqué à réparer : 

[Depuis Validata](https://validata.etalab.studio/table-schema?schema_url=https%3A%2F%2Fschema.data.gouv.fr%2Fschemas%2FNaturalSolutions%2Fschema-arbre%2F0.2.0%2Fschema.json), quand on veut tester la validation des fichiers exemple valides, on rencontre ce message : "Une erreur est survenue lors de la validation". En effet, pour les 2 versions du schéma publiées (`v0.1.0`, `v0.2.0`), les URL des fichiers du champ `resources` sont cassées et par conséquent Validata ne peut pas retrouver les fichiers.

Les URL pointent vers un dépôt `schema-objets-arbre` qui a probablement été renommé en `schema-arbre` par la suite. Par ailleurs, dans la version 0.2.0 du schéma, le tag pointé dans les URL est toujours `v0.1.0` et les informations dans les champs `version` et `lastModified` n'ont pas non plus été mises à jour.

**Comment by mfredout** [comment]
Bonjour, 

Merci du conseil de contacter OpenDataFrance. 
Et merci de nous faire remarquer ce problème ! Nous allons corriger ça le plus rapidement possible.

**Comment by mfredout** [comment]
Des modifications ont été faites, pouvez vous me valider que ça fonctionne pour vous ? 
Merci

**Comment by johanricher** [comment]
Bonjour, les URL ont bien été corrigées dans la version 0.2.0 du schéma (pas dans la 0.1.0 mais c'est pas important) en revanche les informations dans les champs `version` et `lastModified` sont toujours identiques à la version 0.1.0.

**Comment by geoffreyaldebert** [comment]
Merci @johanricher pour tes remarques !

@mfredout j'ai modifié selon les remarques de Johan et créé la pull request #4 . Pouvez-vous la merger ? Il faudra par la suite supprimer et recréer la release 0.2.0 pour que tout soit correct.

Merci !

**Comment by mfredout** [comment]
Bonjour, 

Pardon pour le délai, j'ai merger la pull request 
Est ce que vous pouvez me confirmer que tout est bon ? 

Merci !

**Comment by johanricher** [comment]
J'ai testé la version 0.2.0, la validation du fichier passe, ça m'a l'air nickel. Merci beaucoup. :+1:
