### ISSUE TITLE
Champs manquants ou à modifier

### ISSUE THREAD

**Issue by ghost** [NaturalSolutions/schema-arbre#5]
Il manque les champs : 
description_sol
description_etat_sanitaire
date_releve
geometry (type point coordinates) [montpelllier.json]
circonference
photo_associee [hauts-de-seine.json]

**Comment by Naturantoine** [comment]
diametre_fut [lyon.json]
diametre_couronne [lyon.json]

**Comment by ghost** [comment]
hauteur_fut [lyon.json]
diametre_couronne [lyon.json]

**Comment by ghost** [comment]
houppier (remplacer "port_arbre")
type_feuillage (deciduous_trees) [argenteuil.json]

**Comment by ghost** [comment]
souche
"arbre_mort" ou "trou"
remplacer "age" par "jeune_arbre" ?

**Comment by ghost** [comment]
nichoir

**Comment by ghost** [comment]
infestation_gui

**Comment by ghost** [comment]
taille [bretagne.json] (abattage, entretien, sanitaire, etc.)

**Comment by ghost** [comment]
rive (gauche, droite)

**Comment by ghost** [comment]
remplacer "description_sol" par "pied" [argenteuil.geojson]

**Comment by ghost** [comment]
"critere_historique" histoires et croyances associées à l'arbre
"fruit_comestible"

**Comment by ghost** [comment]
"type_plantation" valeurs multiples permettant de qualifier le type de plantation

**Comment by ghost** [comment]
"environnement" nature de l'environnement dans lequel est positionné l'arbre

**Comment by ghost** [comment]
"positionnement" valeurs multiples permettant de qualifier le positionnement de l'arbre dans son environnement

**Comment by ghost** [comment]
remplacer "code_insee" par "GeoPoint" (valeur unique issus du référentiel national Insee) ?

**Comment by ghost** [comment]
"arbreEntretien" valeurs multiples permettant de qualifier les différentes actions d'entretiens dont peut faire l'objet l'arbre

**Comment by ghost** [comment]
"force" diamètre de l’arbre à 1m du collet
"stade_developpement" liste déroulante 
 Jeune 
 Jeune adulte 
 Adulte
 Sénescent

"type_pied" liste déroulante
 Végétation spontanée
 Semis rustique / prairie fleurie
 Vivaces plantées
 Gazon
 Arbustes
 Pavés enherbés
 Grille acier + paillage
 Résine

"etat_phytosanitaire"
 (score global décrivant l’état général de l’arbre) (liste déroulante à définir)
 Lien vers le/les rapports complets d’expertise sanitaire existants.
 Date de la dernière expertise : jj/mm/aaaa
 Nom de la dernière entreprise d’expertise arboricole
o Commentaire (définir le nombre de caractères)
o Document attaché (photographies)
